name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*


jobs:
  apk:
    name: Generate Apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble App APK
      run: ./gradlew clean assembleDebug
    - name: Upload App APK
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
