name: Android CI

on:
  push:
    branches: 
      - main

jobs:
  apk:
    name: Generate Apk
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug apk
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: :app:clean :app:build
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true

    - name: Upload Debug APK
      uses: actions/upload-artifact@v1
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk
